mysql:
  image: icyleafcn/mariadb
  environment:
    - MYSQL_ROOT_PASSWORD=${mysql_root_password}
    - MYSQL_ALLOW_EMPTY_PASSWORD=${mysql_allow_empty_password}
    - MYSQL_RANDOM_ROOT_PASSWORD=${mysql_random_root_password}
    - MYSQL_USER=${mysql_user}
    - MYSQL_PASSWORD=${mysql_password}
    - MYSQL_DATABASE=${mysql_database}
  ports:
    - ${mysql_port}:3306/tcp