web:
  image: docker.bintray.io/jfrog/artifactory-oss:latest
  ports:
    - ${web_port}:8081/tcp
  volumes:
    - ${artifactory_volume}/data:/var/opt/jfrog/artifactory/data
    - ${artifactory_volume}/logs:/var/opt/jfrog/artifactory/logs
    - ${artifactory_volume}/etc:/var/opt/jfrog/artifactory/etc